import { SorobanClient } from "../soroban.client";
import { MintBurn, init, mintUnderlyingTo } from "../pool.sut";
import { adminKeys, borrower1Keys, lender1Keys } from "../soroban.config";
import {
    convertToScvAddress,
    convertToScvBool,
    convertToScvBytes,
    convertToScvI128,
    convertToScvMap,
    convertToScvVec,
    parseMetaXdrToJs,
} from "../soroban.converter";

describe("LendingPool", function () {
    let client: SorobanClient;

    before(async function () {
        client = new SorobanClient();
        await init(client);
    });

    it("should TBD", async function () {
        let lender1Address = lender1Keys.publicKey();
        let borrower1Address = borrower1Keys.publicKey();

        await client.registerAccount(lender1Address);
        await client.registerAccount(borrower1Address);

        await mintUnderlyingTo(client, "XLM", lender1Address, 100_000_000_000n);
        await mintUnderlyingTo(client, "XRP", lender1Address, 100_000_000_000n);
        await mintUnderlyingTo(client, "USDC", lender1Address, 100_000_000_000n);
        await mintUnderlyingTo(client, "XRP", borrower1Address, 100_000_000_000n);

        // let lender1XlmBalance = await balanceOf(client, lender1Keys, lender1Address, "XLM");
        // let lender1XrpBalance = await balanceOf(client, lender1Keys, lender1Address, "XRP");
        // let lender1UsdcBalance = await balanceOf(client, lender1Keys, lender1Address, "USDC");

        // const lenderDepositResponse = await client.sendTransaction(
        //     process.env.SLENDER_POOL,
        //     "deposit",
        //     lender1Keys,
        //     convertToScvAddress(lender1Address),
        //     convertToScvAddress(process.env.SLENDER_TOKEN_XLM),
        //     convertToScvI128(10000000000n)
        // );
        let asd = "AAAAAwAAAAAAAAACAAAAAwAMKh0AAAAAAAAAAMnXzyc6/cc5B3P8716pFAV5h8y5FGSDjjnAB14NPkRXAAAAF0bjU2MABSsAAAAASQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAAwCwgAAAABk+gNKAAAAAAAAAAEADCodAAAAAAAAAADJ188nOv3HOQdz/O9eqRQFeYfMuRRkg445wAdeDT5EVwAAABdG41NjAAUrAAAAAEoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAAMKh0AAAAAZPrSFwAAAAAAAAABAAAAAwAAAAMADCnqAAAABgAAAAE4iRBVbzDop2Wq+p2GpHZiwW3oTI3a76AyXSAdSXofRwAAABQAAAABAAAAAAAAAAAAAAATAAAAAM3RBNy0dL0wYZf7ckXjA4V1RW9G3PtZT1GdTusWgmpNAAAAAQAAAAsAAAAQAAAAAQAAAAEAAAAPAAAABUFkbWluAAAAAAAAEgAAAAAAAAAAtXT/73M7A3ud/9okY2Wf763Bk96lS8mxWZMh9CXYktMAAAAQAAAAAQAAAAEAAAAPAAAADEZsYXNoTG9hbkZlZQAAAAMAAAAFAAAAEAAAAAEAAAABAAAADwAAAAhJUlBhcmFtcwAAABEAAAABAAAABAAAAA8AAAAFYWxwaGEAAAAAAAADAAAAjwAAAA8AAAAMaW5pdGlhbF9yYXRlAAAAAwAAAMgAAAAPAAAACG1heF9yYXRlAAAAAwAAw1AAAAAPAAAADXNjYWxpbmdfY29lZmYAAAAAAAADAAAjKAAAABAAAAABAAAAAgAAAA8AAAAJUHJpY2VGZWVkAAAAAAAAEgAAAAF7gMN2VxzWKZZColKw8R58WR633SpPJmoKRhWzLJNcSwAAABIAAAABtLFFq7LmQ5/CvWVtv3Fnx8SSJCT+ZEm2239Z1gCkG4EAAAAQAAAAAQAAAAIAAAAPAAAACVByaWNlRmVlZAAAAAAAABIAAAABpk93vak3q2ApJXmrnLrBPAilSH08q8ovTk7Gk5L9TecAAAASAAAAAbSxRauy5kOfwr1lbb9xZ8fEkiQk/mRJttt/WdYApBuBAAAAEAAAAAEAAAACAAAADwAAAAlQcmljZUZlZWQAAAAAAAASAAAAAanArk1Zx05gcT7tcNR8HsaIakcH3j+0pCGXkZtT2bqUAAAAEgAAAAG0sUWrsuZDn8K9ZW2/cWfHxJIkJP5kSbbbf1nWAKQbgQAAABAAAAABAAAAAgAAAA8AAAAPUmVzZXJ2ZUFzc2V0S2V5AAAAABIAAAABe4DDdlcc1imWQqJSsPEefFket90qTyZqCkYVsyyTXEsAAAARAAAAAQAAAAkAAAAPAAAAC2JvcnJvd2VyX2FyAAAAAAoAAAAAAAAAAAAAAAA7msoAAAAADwAAAAtib3Jyb3dlcl9pcgAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAANY29uZmlndXJhdGlvbgAAAAAAABEAAAABAAAACAAAAA8AAAARYm9ycm93aW5nX2VuYWJsZWQAAAAAAAAAAAAAAQAAAA8AAAAIZGVjaW1hbHMAAAADAAAAAAAAAA8AAAAIZGlzY291bnQAAAADAAAXcAAAAA8AAAAJaXNfYWN0aXZlAAAAAAAAAAAAAAEAAAAPAAAADWlzX2Jhc2VfYXNzZXQAAAAAAAAAAAAAAAAAAA8AAAAJbGlxX2JvbnVzAAAAAAAAAwAAKvgAAAAPAAAAB2xpcV9jYXAAAAAACgAAAAAAAAAAAAONfqTGgAAAAAAPAAAACHV0aWxfY2FwAAAAAwAAIygAAAAPAAAAEmRlYnRfdG9rZW5fYWRkcmVzcwAAAAAAEgAAAAHjip0whhLuH8mnW+ePxdNHp2HYvhetCpamgfjCyyAhcAAAAA8AAAACaWQAAAAAAA0AAAABAAAAAAAAAA8AAAAVbGFzdF91cGRhdGVfdGltZXN0YW1wAAAAAAAABQAAAABk+tDeAAAADwAAAAlsZW5kZXJfYXIAAAAAAAAKAAAAAAAAAAAAAAAAO5rKAAAAAA8AAAAJbGVuZGVyX2lyAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAD3NfdG9rZW5fYWRkcmVzcwAAAAASAAAAAbiWuVmpckpH6WzKPg5UhykqooO+Twj/V/E66jTKcwHFAAAAEAAAAAEAAAACAAAADwAAAA9SZXNlcnZlQXNzZXRLZXkAAAAAEgAAAAGmT3e9qTerYCkleaucusE8CKVIfTyryi9OTsaTkv1N5wAAABEAAAABAAAACQAAAA8AAAALYm9ycm93ZXJfYXIAAAAACgAAAAAAAAAAAAAAADuaygAAAAAPAAAAC2JvcnJvd2VyX2lyAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAADwAAAA1jb25maWd1cmF0aW9uAAAAAAAAEQAAAAEAAAAIAAAADwAAABFib3Jyb3dpbmdfZW5hYmxlZAAAAAAAAAAAAAABAAAADwAAAAhkZWNpbWFscwAAAAMAAAAAAAAADwAAAAhkaXNjb3VudAAAAAMAABdwAAAADwAAAAlpc19hY3RpdmUAAAAAAAAAAAAAAQAAAA8AAAANaXNfYmFzZV9hc3NldAAAAAAAAAAAAAAAAAAADwAAAAlsaXFfYm9udXMAAAAAAAADAAAq+AAAAA8AAAAHbGlxX2NhcAAAAAAKAAAAAAAAAAAAA41+pMaAAAAAAA8AAAAIdXRpbF9jYXAAAAADAAAjKAAAAA8AAAASZGVidF90b2tlbl9hZGRyZXNzAAAAAAASAAAAATYBaWJO8AKjtj7u1UwCwYY2g2uAV7hK4k52Wd8YTi1HAAAADwAAAAJpZAAAAAAADQAAAAECAAAAAAAADwAAABVsYXN0X3VwZGF0ZV90aW1lc3RhbXAAAAAAAAAFAAAAAGT60OgAAAAPAAAACWxlbmRlcl9hcgAAAAAAAAoAAAAAAAAAAAAAAAA7msoAAAAADwAAAAlsZW5kZXJfaXIAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAPc190b2tlbl9hZGRyZXNzAAAAABIAAAAB8efj1mRchMDKe+lzoJRIutylpU/HUR5sYFaX6I010SMAAAAQAAAAAQAAAAIAAAAPAAAAD1Jlc2VydmVBc3NldEtleQAAAAASAAAAAanArk1Zx05gcT7tcNR8HsaIakcH3j+0pCGXkZtT2bqUAAAAEQAAAAEAAAAJAAAADwAAAAtib3Jyb3dlcl9hcgAAAAAKAAAAAAAAAAAAAAAAO5rKAAAAAA8AAAALYm9ycm93ZXJfaXIAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAPAAAADWNvbmZpZ3VyYXRpb24AAAAAAAARAAAAAQAAAAgAAAAPAAAAEWJvcnJvd2luZ19lbmFibGVkAAAAAAAAAAAAAAEAAAAPAAAACGRlY2ltYWxzAAAAAwAAAAAAAAAPAAAACGRpc2NvdW50AAAAAwAAF3AAAAAPAAAACWlzX2FjdGl2ZQAAAAAAAAAAAAABAAAADwAAAA1pc19iYXNlX2Fzc2V0AAAAAAAAAAAAAAAAAAAPAAAACWxpcV9ib251cwAAAAAAAAMAACr4AAAADwAAAAdsaXFfY2FwAAAAAAoAAAAAAAAAAAADjX6kxoAAAAAADwAAAAh1dGlsX2NhcAAAAAMAACMoAAAADwAAABJkZWJ0X3Rva2VuX2FkZHJlc3MAAAAAABIAAAABBPfdbiv+NdiXiN6EuM3ShfvQm40mc4aguKytHf2B+z0AAAAPAAAAAmlkAAAAAAANAAAAAQEAAAAAAAAPAAAAFWxhc3RfdXBkYXRlX3RpbWVzdGFtcAAAAAAAAAUAAAAAZPrQ4wAAAA8AAAAJbGVuZGVyX2FyAAAAAAAACgAAAAAAAAAAAAAAADuaygAAAAAPAAAACWxlbmRlcl9pcgAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAADwAAAA9zX3Rva2VuX2FkZHJlc3MAAAAAEgAAAAHLSWojndBwHcuWk2umr3DuNbyC+BHfyETk0S1Uf/d5XwAAABAAAAABAAAAAQAAAA8AAAAIUmVzZXJ2ZXMAAAAQAAAAAQAAAAMAAAASAAAAAXuAw3ZXHNYplkKiUrDxHnxZHrfdKk8magpGFbMsk1xLAAAAEgAAAAGpwK5NWcdOYHE+7XDUfB7GiGpHB94/tKQhl5GbU9m6lAAAABIAAAABpk93vak3q2ApJXmrnLrBPAilSH08q8ovTk7Gk5L9TecAAAAQAAAAAQAAAAEAAAAPAAAACFRyZWFzdXJ5AAAAEgAAAAAAAAAAjcQlaQhOAABKDrnRSx45RwGvbncKJuACgTUv34/figsADXtqAAAAAAAAAAEADCodAAAABgAAAAE4iRBVbzDop2Wq+p2GpHZiwW3oTI3a76AyXSAdSXofRwAAABQAAAABAAAAAAAAAAAAAAATAAAAAM3RBNy0dL0wYZf7ckXjA4V1RW9G3PtZT1GdTusWgmpNAAAAAQAAAA4AAAAQAAAAAQAAAAEAAAAPAAAABUFkbWluAAAAAAAAEgAAAAAAAAAAtXT/73M7A3ud/9okY2Wf763Bk96lS8mxWZMh9CXYktMAAAAQAAAAAQAAAAEAAAAPAAAADEZsYXNoTG9hbkZlZQAAAAMAAAAFAAAAEAAAAAEAAAABAAAADwAAAAhJUlBhcmFtcwAAABEAAAABAAAABAAAAA8AAAAFYWxwaGEAAAAAAAADAAAAjwAAAA8AAAAMaW5pdGlhbF9yYXRlAAAAAwAAAMgAAAAPAAAACG1heF9yYXRlAAAAAwAAw1AAAAAPAAAADXNjYWxpbmdfY29lZmYAAAAAAAADAAAjKAAAABAAAAABAAAAAgAAAA8AAAAJUHJpY2VGZWVkAAAAAAAAEgAAAAF7gMN2VxzWKZZColKw8R58WR633SpPJmoKRhWzLJNcSwAAABIAAAABtLFFq7LmQ5/CvWVtv3Fnx8SSJCT+ZEm2239Z1gCkG4EAAAAQAAAAAQAAAAIAAAAPAAAACVByaWNlRmVlZAAAAAAAABIAAAABpk93vak3q2ApJXmrnLrBPAilSH08q8ovTk7Gk5L9TecAAAASAAAAAbSxRauy5kOfwr1lbb9xZ8fEkiQk/mRJttt/WdYApBuBAAAAEAAAAAEAAAACAAAADwAAAAlQcmljZUZlZWQAAAAAAAASAAAAAanArk1Zx05gcT7tcNR8HsaIakcH3j+0pCGXkZtT2bqUAAAAEgAAAAG0sUWrsuZDn8K9ZW2/cWfHxJIkJP5kSbbbf1nWAKQbgQAAABAAAAABAAAAAgAAAA8AAAAPUmVzZXJ2ZUFzc2V0S2V5AAAAABIAAAABe4DDdlcc1imWQqJSsPEefFket90qTyZqCkYVsyyTXEsAAAARAAAAAQAAAAkAAAAPAAAAC2JvcnJvd2VyX2FyAAAAAAoAAAAAAAAAAAAAAAA7msoAAAAADwAAAAtib3Jyb3dlcl9pcgAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAANY29uZmlndXJhdGlvbgAAAAAAABEAAAABAAAACAAAAA8AAAARYm9ycm93aW5nX2VuYWJsZWQAAAAAAAAAAAAAAQAAAA8AAAAIZGVjaW1hbHMAAAADAAAAAAAAAA8AAAAIZGlzY291bnQAAAADAAAXcAAAAA8AAAAJaXNfYWN0aXZlAAAAAAAAAAAAAAEAAAAPAAAADWlzX2Jhc2VfYXNzZXQAAAAAAAAAAAAAAAAAAA8AAAAJbGlxX2JvbnVzAAAAAAAAAwAAKvgAAAAPAAAAB2xpcV9jYXAAAAAACgAAAAAAAAAAAAONfqTGgAAAAAAPAAAACHV0aWxfY2FwAAAAAwAAIygAAAAPAAAAEmRlYnRfdG9rZW5fYWRkcmVzcwAAAAAAEgAAAAHjip0whhLuH8mnW+ePxdNHp2HYvhetCpamgfjCyyAhcAAAAA8AAAACaWQAAAAAAA0AAAABAAAAAAAAAA8AAAAVbGFzdF91cGRhdGVfdGltZXN0YW1wAAAAAAAABQAAAABk+tIXAAAADwAAAAlsZW5kZXJfYXIAAAAAAAAKAAAAAAAAAAAAAAAAO5rKAAAAAA8AAAAJbGVuZGVyX2lyAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAD3NfdG9rZW5fYWRkcmVzcwAAAAASAAAAAbiWuVmpckpH6WzKPg5UhykqooO+Twj/V/E66jTKcwHFAAAAEAAAAAEAAAACAAAADwAAAA9SZXNlcnZlQXNzZXRLZXkAAAAAEgAAAAGmT3e9qTerYCkleaucusE8CKVIfTyryi9OTsaTkv1N5wAAABEAAAABAAAACQAAAA8AAAALYm9ycm93ZXJfYXIAAAAACgAAAAAAAAAAAAAAADuaygAAAAAPAAAAC2JvcnJvd2VyX2lyAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAADwAAAA1jb25maWd1cmF0aW9uAAAAAAAAEQAAAAEAAAAIAAAADwAAABFib3Jyb3dpbmdfZW5hYmxlZAAAAAAAAAAAAAABAAAADwAAAAhkZWNpbWFscwAAAAMAAAAAAAAADwAAAAhkaXNjb3VudAAAAAMAABdwAAAADwAAAAlpc19hY3RpdmUAAAAAAAAAAAAAAQAAAA8AAAANaXNfYmFzZV9hc3NldAAAAAAAAAAAAAAAAAAADwAAAAlsaXFfYm9udXMAAAAAAAADAAAq+AAAAA8AAAAHbGlxX2NhcAAAAAAKAAAAAAAAAAAAA41+pMaAAAAAAA8AAAAIdXRpbF9jYXAAAAADAAAjKAAAAA8AAAASZGVidF90b2tlbl9hZGRyZXNzAAAAAAASAAAAATYBaWJO8AKjtj7u1UwCwYY2g2uAV7hK4k52Wd8YTi1HAAAADwAAAAJpZAAAAAAADQAAAAECAAAAAAAADwAAABVsYXN0X3VwZGF0ZV90aW1lc3RhbXAAAAAAAAAFAAAAAGT60OgAAAAPAAAACWxlbmRlcl9hcgAAAAAAAAoAAAAAAAAAAAAAAAA7msoAAAAADwAAAAlsZW5kZXJfaXIAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAPc190b2tlbl9hZGRyZXNzAAAAABIAAAAB8efj1mRchMDKe+lzoJRIutylpU/HUR5sYFaX6I010SMAAAAQAAAAAQAAAAIAAAAPAAAAD1Jlc2VydmVBc3NldEtleQAAAAASAAAAAanArk1Zx05gcT7tcNR8HsaIakcH3j+0pCGXkZtT2bqUAAAAEQAAAAEAAAAJAAAADwAAAAtib3Jyb3dlcl9hcgAAAAAKAAAAAAAAAAAAAAAAO5rKAAAAAA8AAAALYm9ycm93ZXJfaXIAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAPAAAADWNvbmZpZ3VyYXRpb24AAAAAAAARAAAAAQAAAAgAAAAPAAAAEWJvcnJvd2luZ19lbmFibGVkAAAAAAAAAAAAAAEAAAAPAAAACGRlY2ltYWxzAAAAAwAAAAAAAAAPAAAACGRpc2NvdW50AAAAAwAAF3AAAAAPAAAACWlzX2FjdGl2ZQAAAAAAAAAAAAABAAAADwAAAA1pc19iYXNlX2Fzc2V0AAAAAAAAAAAAAAAAAAAPAAAACWxpcV9ib251cwAAAAAAAAMAACr4AAAADwAAAAdsaXFfY2FwAAAAAAoAAAAAAAAAAAADjX6kxoAAAAAADwAAAAh1dGlsX2NhcAAAAAMAACMoAAAADwAAABJkZWJ0X3Rva2VuX2FkZHJlc3MAAAAAABIAAAABBPfdbiv+NdiXiN6EuM3ShfvQm40mc4aguKytHf2B+z0AAAAPAAAAAmlkAAAAAAANAAAAAQEAAAAAAAAPAAAAFWxhc3RfdXBkYXRlX3RpbWVzdGFtcAAAAAAAAAUAAAAAZPrQ4wAAAA8AAAAJbGVuZGVyX2FyAAAAAAAACgAAAAAAAAAAAAAAADuaygAAAAAPAAAACWxlbmRlcl9pcgAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAADwAAAA9zX3Rva2VuX2FkZHJlc3MAAAAAEgAAAAHLSWojndBwHcuWk2umr3DuNbyC+BHfyETk0S1Uf/d5XwAAABAAAAABAAAAAQAAAA8AAAAIUmVzZXJ2ZXMAAAAQAAAAAQAAAAMAAAASAAAAAXuAw3ZXHNYplkKiUrDxHnxZHrfdKk8magpGFbMsk1xLAAAAEgAAAAGpwK5NWcdOYHE+7XDUfB7GiGpHB94/tKQhl5GbU9m6lAAAABIAAAABpk93vak3q2ApJXmrnLrBPAilSH08q8ovTk7Gk5L9TecAAAAQAAAAAQAAAAIAAAAPAAAAF1NUb2tlblVuZGVybHlpbmdCYWxhbmNlAAAAABIAAAABuJa5WalySkfpbMo+DlSHKSqig75PCP9X8TrqNMpzAcUAAAAKAAAAAAAAAAAAAAACVAvkAAAAABAAAAABAAAAAwAAAA8AAAAMVG9rZW5CYWxhbmNlAAAAEgAAAAG4lrlZqXJKR+lsyj4OVIcpKqKDvk8I/1fxOuo0ynMBxQAAABIAAAAAAAAAAMnXzyc6/cc5B3P8716pFAV5h8y5FGSDjjnAB14NPkRXAAAACgAAAAAAAAAAAAAAAlQL5AAAAAAQAAAAAQAAAAIAAAAPAAAAC1Rva2VuU3VwcGx5AAAAABIAAAABuJa5WalySkfpbMo+DlSHKSqig75PCP9X8TrqNMpzAcUAAAAKAAAAAAAAAAAAAAACVAvkAAAAABAAAAABAAAAAQAAAA8AAAAIVHJlYXN1cnkAAAASAAAAAAAAAACNxCVpCE4AAEoOudFLHjlHAa9udwom4AKBNS/fj9+KCwANe2oAAAAAAAAAAAAMKh0AAAAGAAAAATiJEFVvMOinZar6nYakdmLBbehMjdrvoDJdIB1Jeh9HAAAAEAAAAAEAAAACAAAADwAAAApVc2VyQ29uZmlnAAAAAAASAAAAAAAAAADJ188nOv3HOQdz/O9eqRQFeYfMuRRkg445wAdeDT5EVwAAAAEAAAAAAAAAAAAAABAAAAABAAAAAQAAAAkAAAAAAAAAAAAAAAAAAAACABQTHQAAAAAAAAACAAAAAwAMKh0AAAAAAAAAAMnXzyc6/cc5B3P8716pFAV5h8y5FGSDjjnAB14NPkRXAAAAF0bjU2MABSsAAAAASgAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAAwqHQAAAABk+tIXAAAAAAAAAAEADCodAAAAAAAAAADJ188nOv3HOQdz/O9eqRQFeYfMuRRkg445wAdeDT5EVwAAABdG41QgAAUrAAAAAEoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAAMKh0AAAAAZPrSFwAAAAAAAAABAAAAAAAAAAIAAAAAAAAAATiJEFVvMOinZar6nYakdmLBbehMjdrvoDJdIB1Jeh9HAAAAAQAAAAAAAAACAAAADwAAABxyZXNlcnZlX3VzZWRfYXNfY29sbF9lbmFibGVkAAAAEgAAAAAAAAAAydfPJzr9xzkHc/zvXqkUBXmHzLkUZIOOOcAHXg0+RFcAAAASAAAAAXuAw3ZXHNYplkKiUrDxHnxZHrfdKk8magpGFbMsk1xLAAAAAAAAAAE4iRBVbzDop2Wq+p2GpHZiwW3oTI3a76AyXSAdSXofRwAAAAEAAAAAAAAAAgAAAA8AAAAHZGVwb3NpdAAAAAASAAAAAAAAAADJ188nOv3HOQdz/O9eqRQFeYfMuRRkg445wAdeDT5EVwAAABAAAAABAAAAAgAAABIAAAABe4DDdlcc1imWQqJSsPEefFket90qTyZqCkYVsyyTXEsAAAAKAAAAAAAAAAAAAAACVAvkAAAAABAAAAABAAAAAwAAABEAAAABAAAAAwAAAA8AAAANYXNzZXRfYmFsYW5jZQAAAAAAABEAAAABAAAAAgAAAA8AAAAFYXNzZXQAAAAAAAASAAAAAXuAw3ZXHNYplkKiUrDxHnxZHrfdKk8magpGFbMsk1xLAAAADwAAAAdiYWxhbmNlAAAAAAoAAAAAAAAAAAAAAAJUC+QAAAAADwAAAARtaW50AAAAAAAAAAAAAAAPAAAAA3dobwAAAAASAAAAAAAAAADJ188nOv3HOQdz/O9eqRQFeYfMuRRkg445wAdeDT5EVwAAABEAAAABAAAAAwAAAA8AAAANYXNzZXRfYmFsYW5jZQAAAAAAABEAAAABAAAAAgAAAA8AAAAFYXNzZXQAAAAAAAASAAAAAXuAw3ZXHNYplkKiUrDxHnxZHrfdKk8magpGFbMsk1xLAAAADwAAAAdiYWxhbmNlAAAAAAoAAAAAAAAAAAAAAAJUC+QAAAAADwAAAARtaW50AAAAAAAAAAEAAAAPAAAAA3dobwAAAAASAAAAAbiWuVmpckpH6WzKPg5UhykqooO+Twj/V/E66jTKcwHFAAAAEQAAAAEAAAADAAAADwAAAA1hc3NldF9iYWxhbmNlAAAAAAAAEQAAAAEAAAACAAAADwAAAAVhc3NldAAAAAAAABIAAAABuJa5WalySkfpbMo+DlSHKSqig75PCP9X8TrqNMpzAcUAAAAPAAAAB2JhbGFuY2UAAAAACgAAAAAAAAAAAAAAAlQL5AAAAAAPAAAABG1pbnQAAAAAAAAAAQAAAA8AAAADd2hvAAAAABIAAAAAAAAAAMnXzyc6/cc5B3P8716pFAV5h8y5FGSDjjnAB14NPkRXAAAAAA=="

        const lenderDepositResult = parseMetaXdrToJs<Array<MintBurn>>(asd);
        for (let i = 0; i < lenderDepositResult.length; i++) {
            if (lenderDepositResult[i].mint) {
                await client.sendTransaction(
                    lenderDepositResult[i].asset_balance.asset.toString(),
                    "mint",
                    adminKeys,
                    convertToScvAddress(lenderDepositResult[i].who.toString()),
                    convertToScvI128(lenderDepositResult[i].asset_balance.balance)
                );
            } else {
                await client.sendTransaction(
                    lenderDepositResult[i].asset_balance.asset.toString(),
                    "mint",
                    adminKeys,
                    convertToScvAddress(lenderDepositResult[i].who.toString()),
                    convertToScvI128(lenderDepositResult[i].asset_balance.balance)
                );
            }


        }
        // const lenderDepositResult = parseMetaXdrToJs<>(
        //     lenderDepositResponse.resultMetaXdr
        // );


        const borrowerDepositResponse = await client.sendTransaction(
            process.env.SLENDER_POOL,
            "deposit",
            borrower1Keys,
            convertToScvAddress(borrower1Address),
            convertToScvAddress(process.env.SLENDER_TOKEN_XRP),
            convertToScvI128(10000000000n)
        );
        const borrowerDepositResult = parseMetaXdrToJs(
            borrowerDepositResponse.resultMetaXdr
        );

        const borrowerBorrowResponse = await client.sendTransaction(
            process.env.SLENDER_POOL,
            "borrow",
            borrower1Keys,
            convertToScvAddress(borrower1Address),
            convertToScvAddress(process.env.SLENDER_TOKEN_XLM),
            convertToScvI128(10000000n)
        );
        const borrowerBorrowResult = parseMetaXdrToJs(
            borrowerBorrowResponse.resultMetaXdr
        );
        console.log(JSON.stringify(borrowerBorrowResult, null, 2));

        const lenderWithdrawResponse = await client.sendTransaction(
            process.env.SLENDER_POOL,
            "withdraw",
            lender1Keys,
            convertToScvAddress(lender1Address),
            convertToScvAddress(process.env.SLENDER_TOKEN_XLM),
            convertToScvI128(100000n),
            convertToScvAddress(lender1Address),
        );
        const lenderWithdrawResult = parseMetaXdrToJs(
            lenderWithdrawResponse.resultMetaXdr
        );
        console.log(JSON.stringify(lenderWithdrawResult, null, 2));

        const borrowerRepayResponse = await client.sendTransaction(
            process.env.SLENDER_POOL,
            "repay",
            borrower1Keys,
            convertToScvAddress(borrower1Address),
            convertToScvAddress(process.env.SLENDER_TOKEN_XLM),
            convertToScvI128(1000000n),
        );
        const borrowerRepayResult = parseMetaXdrToJs(
            borrowerRepayResponse.resultMetaXdr
        );
        console.log(JSON.stringify(borrowerRepayResult, null, 2));

        const flashLoanResponse = await client.sendTransaction(
            process.env.SLENDER_POOL,
            "flash_loan",
            borrower1Keys,
            convertToScvAddress(borrower1Address),
            convertToScvAddress(process.env.FLASH_LOAN_RECEIVER),
            convertToScvVec([
                convertToScvMap({
                    "amount": convertToScvI128(1000n),
                    "asset": convertToScvAddress(process.env.SLENDER_TOKEN_XLM),
                    "borrow": convertToScvBool(false)
                })
            ]),
            convertToScvBytes("test", "base64"),
        );
        const flashLoanResult = parseMetaXdrToJs(
            flashLoanResponse.resultMetaXdr
        );
        console.log(JSON.stringify(flashLoanResult, null, 2));
    });
});
